version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3001:3001"
      - "50051:50051"
    environment:
      - PORT=3001
      - GRPC_PORT=50051
      - DATABASE_URL=postgresql://admin:password@postgres:5432/auth_db?schema=public
      - JWT_SECRET=supersecret123
    depends_on:
      - postgres
    volumes:
      - ./protos:/usr/src/app/protos

  product-service:
    build:
      context: ./product-service
    ports:
      - "3002:3002"
      - "50052:50052"
    environment:
      - PORT=3002
      - GRPC_PORT=50052
      - DATABASE_URL=postgresql://admin:password@postgres:5432/product_db?schema=public
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - AUTH_GRPC_URL=auth-service:50051
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./protos:/usr/src/app/protos

  order-service:
    build:
      context: ./order-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DATABASE_URL=postgresql://admin:password@postgres:5432/order_db?schema=public
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672
      - AUTH_GRPC_URL=auth-service:50051
      - PRODUCT_GRPC_URL=product-service:50052
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./protos:/usr/src/app/protos
